### ISSUE TITLE
Error: name 'puzzle' is not defined

### ISSUE THREAD

**Issue by triggerhappy88** [JaneHJY/8_puzzle#1]
Hi, i copied your code and pasted it on pycharm and tried to run it but im getting some errors :(

**Comment by triggerhappy88** [comment]
C:\Users\asus\PycharmProjects\ChE297_Jan22\venv\Scripts\python.exe C:/Users/asus/.PyCharmCE2019.2/config/scratches/ChE297_HW4.py
Traceback (most recent call last):
  File "C:/Users/asus/.PyCharmCE2019.2/config/scratches/ChE297_HW4.py", line 96, in <module>
    class Puzzle:
  File "C:/Users/asus/.PyCharmCE2019.2/config/scratches/ChE297_HW4.py", line 194, in Puzzle
    puzzle = puzzle(board)
NameError: name 'puzzle' is not defined

Process finished with exit code 1

**Comment by av1m** [comment]
You copied incorrectly
You need to use `P` instead of `p`.
Your line (wrong) : `puzzle = puzzle(board)`
Correct line : `puzzle = Puzzle(board)`
